### ISSUE TITLE
confusing prompt message

### ISSUE THREAD

**Issue by AtefBN** [ESGF/esgf-download#4]
![image](https://user-images.githubusercontent.com/15193639/233368995-b7f77fd1-c943-47e2-9576-abdef3c94c1f.png)
Probably requires further user input sanitization and considering upper/lowercase all the same

**Comment by svenrdz** [comment]
This works fine on my computer, in both upper and lower case.
Are you sure there was no hidden extra input in the first try, for example on a previous line before the prompt appears ?
I think the `rich` library I used for prompting is getting the input from stdin, it might explain that.
